
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T19:14:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "64b7a9a7d24b86a3279043a06216ada086e96eb9",
 "version": "0.0.1.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
