"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import th2_grpc_generator_template.Foo_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Bar(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FOO_FIELD_NUMBER: builtins.int

    @property
    def foo(self) -> th2_grpc_generator_template.Foo_pb2.Foo: ...

    def __init__(self,
        *,
        foo : typing.Optional[th2_grpc_generator_template.Foo_pb2.Foo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"foo",b"foo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"foo",b"foo"]) -> None: ...
global___Bar = Bar
