# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='account_service.proto',
  package='calixa.domain.account',
  syntax='proto3',
  serialized_options=b'\n\030io.calixa.domain.accountH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x61\x63\x63ount_service.proto\x12\x15\x63\x61lixa.domain.account\x1a\x0c\x63ommon.proto\x1a\x0c\x65ntity.proto\"X\n\x1cSaveOpportunityEntityRequest\x12\x38\n\x12opportunity_entity\x18\x03 \x01(\x0b\x32\x1c.calixa.domain.entity.Entity\"\xc9\x01\n SaveExternalAccountEntityRequest\x12\x35\n\x0f\x65xternal_entity\x18\x02 \x01(\x0b\x32\x1c.calixa.domain.entity.Entity\x12I\n\x1brelated_external_entity_ids\x18\x03 \x03(\x0b\x32 .calixa.domain.common.ExternalIdB\x02\x18\x01\x12#\n\x17\x65xternal_api_account_id\x18\x04 \x01(\tB\x02\x18\x01\"\xa8\x01\n$SaveExternalAccountUserEntityRequest\x12\x35\n\x0f\x65xternal_entity\x18\x02 \x01(\x0b\x32\x1c.calixa.domain.entity.Entity\x12I\n\x1brelated_external_entity_ids\x18\x03 \x03(\x0b\x32 .calixa.domain.common.ExternalIdB\x02\x18\x01\x32\xfb\x02\n\x0e\x41\x63\x63ountService\x12o\n\x15SaveOpportunityEntity\x12\x33.calixa.domain.account.SaveOpportunityEntityRequest\x1a\x1c.calixa.domain.entity.Entity\"\x03\x88\x02\x01\x12w\n\x19SaveExternalAccountEntity\x12\x37.calixa.domain.account.SaveExternalAccountEntityRequest\x1a\x1c.calixa.domain.entity.Entity\"\x03\x88\x02\x01\x12\x7f\n\x1dSaveExternalAccountUserEntity\x12;.calixa.domain.account.SaveExternalAccountUserEntityRequest\x1a\x1c.calixa.domain.entity.Entity\"\x03\x88\x02\x01\x42\x1e\n\x18io.calixa.domain.accountH\x01P\x01\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,entity__pb2.DESCRIPTOR,])




_SAVEOPPORTUNITYENTITYREQUEST = _descriptor.Descriptor(
  name='SaveOpportunityEntityRequest',
  full_name='calixa.domain.account.SaveOpportunityEntityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opportunity_entity', full_name='calixa.domain.account.SaveOpportunityEntityRequest.opportunity_entity', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=164,
)


_SAVEEXTERNALACCOUNTENTITYREQUEST = _descriptor.Descriptor(
  name='SaveExternalAccountEntityRequest',
  full_name='calixa.domain.account.SaveExternalAccountEntityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='external_entity', full_name='calixa.domain.account.SaveExternalAccountEntityRequest.external_entity', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='related_external_entity_ids', full_name='calixa.domain.account.SaveExternalAccountEntityRequest.related_external_entity_ids', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='external_api_account_id', full_name='calixa.domain.account.SaveExternalAccountEntityRequest.external_api_account_id', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=368,
)


_SAVEEXTERNALACCOUNTUSERENTITYREQUEST = _descriptor.Descriptor(
  name='SaveExternalAccountUserEntityRequest',
  full_name='calixa.domain.account.SaveExternalAccountUserEntityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='external_entity', full_name='calixa.domain.account.SaveExternalAccountUserEntityRequest.external_entity', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='related_external_entity_ids', full_name='calixa.domain.account.SaveExternalAccountUserEntityRequest.related_external_entity_ids', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=539,
)

_SAVEOPPORTUNITYENTITYREQUEST.fields_by_name['opportunity_entity'].message_type = entity__pb2._ENTITY
_SAVEEXTERNALACCOUNTENTITYREQUEST.fields_by_name['external_entity'].message_type = entity__pb2._ENTITY
_SAVEEXTERNALACCOUNTENTITYREQUEST.fields_by_name['related_external_entity_ids'].message_type = common__pb2._EXTERNALID
_SAVEEXTERNALACCOUNTUSERENTITYREQUEST.fields_by_name['external_entity'].message_type = entity__pb2._ENTITY
_SAVEEXTERNALACCOUNTUSERENTITYREQUEST.fields_by_name['related_external_entity_ids'].message_type = common__pb2._EXTERNALID
DESCRIPTOR.message_types_by_name['SaveOpportunityEntityRequest'] = _SAVEOPPORTUNITYENTITYREQUEST
DESCRIPTOR.message_types_by_name['SaveExternalAccountEntityRequest'] = _SAVEEXTERNALACCOUNTENTITYREQUEST
DESCRIPTOR.message_types_by_name['SaveExternalAccountUserEntityRequest'] = _SAVEEXTERNALACCOUNTUSERENTITYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaveOpportunityEntityRequest = _reflection.GeneratedProtocolMessageType('SaveOpportunityEntityRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEOPPORTUNITYENTITYREQUEST,
  '__module__' : 'account_service_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.account.SaveOpportunityEntityRequest)
  })
_sym_db.RegisterMessage(SaveOpportunityEntityRequest)

SaveExternalAccountEntityRequest = _reflection.GeneratedProtocolMessageType('SaveExternalAccountEntityRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEEXTERNALACCOUNTENTITYREQUEST,
  '__module__' : 'account_service_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.account.SaveExternalAccountEntityRequest)
  })
_sym_db.RegisterMessage(SaveExternalAccountEntityRequest)

SaveExternalAccountUserEntityRequest = _reflection.GeneratedProtocolMessageType('SaveExternalAccountUserEntityRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEEXTERNALACCOUNTUSERENTITYREQUEST,
  '__module__' : 'account_service_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.account.SaveExternalAccountUserEntityRequest)
  })
_sym_db.RegisterMessage(SaveExternalAccountUserEntityRequest)


DESCRIPTOR._options = None
_SAVEEXTERNALACCOUNTENTITYREQUEST.fields_by_name['related_external_entity_ids']._options = None
_SAVEEXTERNALACCOUNTENTITYREQUEST.fields_by_name['external_api_account_id']._options = None
_SAVEEXTERNALACCOUNTUSERENTITYREQUEST.fields_by_name['related_external_entity_ids']._options = None

_ACCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='AccountService',
  full_name='calixa.domain.account.AccountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=542,
  serialized_end=921,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveOpportunityEntity',
    full_name='calixa.domain.account.AccountService.SaveOpportunityEntity',
    index=0,
    containing_service=None,
    input_type=_SAVEOPPORTUNITYENTITYREQUEST,
    output_type=entity__pb2._ENTITY,
    serialized_options=b'\210\002\001',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SaveExternalAccountEntity',
    full_name='calixa.domain.account.AccountService.SaveExternalAccountEntity',
    index=1,
    containing_service=None,
    input_type=_SAVEEXTERNALACCOUNTENTITYREQUEST,
    output_type=entity__pb2._ENTITY,
    serialized_options=b'\210\002\001',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SaveExternalAccountUserEntity',
    full_name='calixa.domain.account.AccountService.SaveExternalAccountUserEntity',
    index=2,
    containing_service=None,
    input_type=_SAVEEXTERNALACCOUNTUSERENTITYREQUEST,
    output_type=entity__pb2._ENTITY,
    serialized_options=b'\210\002\001',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCOUNTSERVICE)

DESCRIPTOR.services_by_name['AccountService'] = _ACCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
