
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T16:10:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "52321b36494c07616afaff83f5069705e7396091",
 "version": "0.2.59.post0.dev32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
