
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T12:54:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "11c55f2e72edfeb3395bdbdb7d1b5a0114e14ecf",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
