
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T06:33:57-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0956417a5b5b9b72686136742b84d99fa5d7958",
 "version": "3.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
