
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T09:58:00+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd5f4623eac786cab18850e2e34ac88829c99a06",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
