
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T10:21:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "85af847aa286e8034f185c6b2cc4298997c0724c",
 "version": "1.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
