# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from common_pb2 import (
    ExternalId as common_pb2___ExternalId,
)

from entity_pb2 import (
    Entity as entity_pb2___Entity,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class SaveOpportunityEntityRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def opportunity_entity(self) -> entity_pb2___Entity: ...

    def __init__(self,
        *,
        opportunity_entity : typing___Optional[entity_pb2___Entity] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"opportunity_entity",b"opportunity_entity"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"opportunity_entity",b"opportunity_entity"]) -> None: ...
type___SaveOpportunityEntityRequest = SaveOpportunityEntityRequest

class SaveExternalAccountEntityRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    external_api_account_id: typing___Text = ...

    @property
    def external_entity(self) -> entity_pb2___Entity: ...

    @property
    def related_external_entity_ids(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[common_pb2___ExternalId]: ...

    def __init__(self,
        *,
        external_entity : typing___Optional[entity_pb2___Entity] = None,
        related_external_entity_ids : typing___Optional[typing___Iterable[common_pb2___ExternalId]] = None,
        external_api_account_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"external_entity",b"external_entity"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"external_api_account_id",b"external_api_account_id",u"external_entity",b"external_entity",u"related_external_entity_ids",b"related_external_entity_ids"]) -> None: ...
type___SaveExternalAccountEntityRequest = SaveExternalAccountEntityRequest

class SaveExternalAccountUserEntityRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def external_entity(self) -> entity_pb2___Entity: ...

    @property
    def related_external_entity_ids(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[common_pb2___ExternalId]: ...

    def __init__(self,
        *,
        external_entity : typing___Optional[entity_pb2___Entity] = None,
        related_external_entity_ids : typing___Optional[typing___Iterable[common_pb2___ExternalId]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"external_entity",b"external_entity"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"external_entity",b"external_entity",u"related_external_entity_ids",b"related_external_entity_ids"]) -> None: ...
type___SaveExternalAccountUserEntityRequest = SaveExternalAccountUserEntityRequest
