# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import account_service_pb2 as account__service__pb2
import entity_pb2 as entity__pb2


class AccountServiceStub(object):
    """THIS SERVICE IS DEPRECATED; Use EntityService#SaveEntity instead.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveOpportunityEntity = channel.unary_unary(
                '/calixa.domain.account.AccountService/SaveOpportunityEntity',
                request_serializer=account__service__pb2.SaveOpportunityEntityRequest.SerializeToString,
                response_deserializer=entity__pb2.Entity.FromString,
                )
        self.SaveExternalAccountEntity = channel.unary_unary(
                '/calixa.domain.account.AccountService/SaveExternalAccountEntity',
                request_serializer=account__service__pb2.SaveExternalAccountEntityRequest.SerializeToString,
                response_deserializer=entity__pb2.Entity.FromString,
                )
        self.SaveExternalAccountUserEntity = channel.unary_unary(
                '/calixa.domain.account.AccountService/SaveExternalAccountUserEntity',
                request_serializer=account__service__pb2.SaveExternalAccountUserEntityRequest.SerializeToString,
                response_deserializer=entity__pb2.Entity.FromString,
                )


class AccountServiceServicer(object):
    """THIS SERVICE IS DEPRECATED; Use EntityService#SaveEntity instead.
    """

    def SaveOpportunityEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveExternalAccountEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveExternalAccountUserEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveOpportunityEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveOpportunityEntity,
                    request_deserializer=account__service__pb2.SaveOpportunityEntityRequest.FromString,
                    response_serializer=entity__pb2.Entity.SerializeToString,
            ),
            'SaveExternalAccountEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveExternalAccountEntity,
                    request_deserializer=account__service__pb2.SaveExternalAccountEntityRequest.FromString,
                    response_serializer=entity__pb2.Entity.SerializeToString,
            ),
            'SaveExternalAccountUserEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveExternalAccountUserEntity,
                    request_deserializer=account__service__pb2.SaveExternalAccountUserEntityRequest.FromString,
                    response_serializer=entity__pb2.Entity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calixa.domain.account.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """THIS SERVICE IS DEPRECATED; Use EntityService#SaveEntity instead.
    """

    @staticmethod
    def SaveOpportunityEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.account.AccountService/SaveOpportunityEntity',
            account__service__pb2.SaveOpportunityEntityRequest.SerializeToString,
            entity__pb2.Entity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveExternalAccountEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.account.AccountService/SaveExternalAccountEntity',
            account__service__pb2.SaveExternalAccountEntityRequest.SerializeToString,
            entity__pb2.Entity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveExternalAccountUserEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.account.AccountService/SaveExternalAccountUserEntity',
            account__service__pb2.SaveExternalAccountUserEntityRequest.SerializeToString,
            entity__pb2.Entity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
