
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-14T11:20:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ead1ef7d74f60e88408fa1feb196e867858fc48a",
 "version": "2023.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
