
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T15:13:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "38ba649ff929f9615049cdf0e0e52959def2c75c",
 "version": "1.13.107"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
