
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T23:20:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed4ed354b93262b04a38ee7b3c756aed44983b50",
 "version": "0.14.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
