from typing import ClassVar

import pydrake.systems.framework
import pydrake.systems.lcm

class ZeroForceDriver:
    __fields__: ClassVar[tuple] = ...  # read-only
    def __init__(self, **kwargs) -> None: ...
    def __copy__(self) -> ZeroForceDriver: ...
    def __deepcopy__(self, arg0: dict) -> ZeroForceDriver: ...

def ApplyDriverConfig(driver_config: ZeroForceDriver, model_instance_name: str, sim_plant, models_from_directives, lcms: pydrake.systems.lcm.LcmBuses, builder: pydrake.systems.framework.DiagramBuilder_[float]) -> None: ...
