
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T15:58:28+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f525231309246508e03ba3ec787d41c9a001458",
 "version": "0.16.3.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
