"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Options(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAX_COUNT_FIELD_NUMBER: builtins.int
    FIXED_COUNT_FIELD_NUMBER: builtins.int
    MAX_SIZE_FIELD_NUMBER: builtins.int
    FIXED_SIZE_FIELD_NUMBER: builtins.int
    USE_CALLBACK_FIELD_NUMBER: builtins.int
    max_count: builtins.int
    """Maximum number of entries for repeated fields."""

    fixed_count: builtins.bool
    """Use a fixed length std::array for repeated fields instead of pw::Vector."""

    max_size: builtins.int
    """Maximum size for bytes and string fields."""

    fixed_size: builtins.bool
    """Use a fixed size std::array for bytes fields instead of pw::Vector."""

    use_callback: builtins.bool
    """Force the use of a callback function for the field."""

    def __init__(self,
        *,
        max_count: builtins.int = ...,
        fixed_count: builtins.bool = ...,
        max_size: builtins.int = ...,
        fixed_size: builtins.bool = ...,
        use_callback: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fixed_count",b"fixed_count","fixed_size",b"fixed_size","max_count",b"max_count","max_size",b"max_size","use_callback",b"use_callback"]) -> None: ...
global___Options = Options
