
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T12:47:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "48cb12ea59c4433b73ad354b3b1991e25ca839dd",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
