
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T12:41:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e60bdb6e404eba0a495ce5d11d6265e24bd0efe5",
 "version": "4.1.54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
