
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-28T22:14:35-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "bae99140036d0d4fb08a0c14a89d2e03436b198e",
 "version": "0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
