
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T15:57:00-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "53520f5a2d2bbd4b49eb865bc5e1fcb5d77e613b",
 "version": "0.2.60.post0.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
