
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-14T09:51:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0caccee1dfda57d373e7c037f2bfc29a2ee6e9c3",
 "version": "0.10.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
