
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T09:53:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "282f197136d6171203f4457dd79da7bb943b28c8",
 "version": "0.0.13rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
