# Generated by Django 4.1.5 on 2023-01-11 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recomb_to_s3.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecombToS3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=recomb_to_s3.utils.directory_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "uploaded file",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
