
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T10:12:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "67688d9cbac3b4d716d0ab50fd6fb3e9cad3f8c1",
 "version": "1.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
