
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T14:00:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdb7b565e92eb79080eadd82482bdac9d1ca0c64",
 "version": "v23.02.00a230111"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
