
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T15:03:31+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7c7b029c9c089f044721d6773417d8e91632dd9",
 "version": "0.17.2a8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
