
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T16:32:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16a38ee54122f3af567742010e184a24e1cd84cb",
 "version": "2023.1rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
