
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T21:27:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2d379c0c385078b1eb3de9b5908af7d48e4fc76",
 "version": "0.2.60.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
