
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T14:53:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9935a526b2881f5f0e4279096a8f301ab4e6f9b7",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
