
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T15:26:53+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "cefb325dd2eca97d2ffa744bb3cf4fa1d5704af1",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
