VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('11')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('42')
MAJOR_VERSION = 0
MINOR_VERSION = 13
PATCH_VERSION = 202301110642
version_date = '2023/01/11 06:42'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
