
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T14:54:36-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1295dc9152c5bd54682f9e4dc91b6841cae7656e",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
