
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T10:44:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff6acbea311051e9408d25c76fb8ccc8cb689c29",
 "version": "0.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
