
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T19:59:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "84eb87cefe4b6f784545b0f5e07437a83e0f48a1",
 "version": "0.2.59.post0.dev22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
