
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-09T22:11:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee3e5c2e2a3d436a2d4d9b69f526328d7c1e5b4b",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
