
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T22:14:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c50eac4cdf0755fcee892669831c2af54aae904",
 "version": "0.2.60.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
