# coding: utf-8

# flake8: noqa

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from commonfate.api_client import ApiClient

# import Configuration
from commonfate.configuration import Configuration

# import exceptions
from commonfate.exceptions import OpenApiException
from commonfate.exceptions import ApiAttributeError
from commonfate.exceptions import ApiTypeError
from commonfate.exceptions import ApiValueError
from commonfate.exceptions import ApiKeyError
from commonfate.exceptions import ApiException
