
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T07:40:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "894a2aee042d97c0814ccbd3aa9e0c8eb1af490a",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
