
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T11:18:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6a4735fcffa0fbd3a03ddf8007a7836d0b10d28",
 "version": "1.17.1.post0.dev1003"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
