
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T18:32:03-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0ad8145a083b01edd307a26620bd4081fed2448",
 "version": "3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
