
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-09T12:06:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b32649c8df2029fbd25dd18716fe838e0c62d6ae",
 "version": "v0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
