
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T04:35:14-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "986d3fab51050676696f20b31295483f3f61e4e6",
 "version": "4.9.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
