
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T07:48:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1b112eca16984ebeb85b47a50fc9f85f4e4bfea",
 "version": "2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
