
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: //:liga

from setuptools import setup

setup(**{
    'install_requires': (
        'antlr4-python3-runtime==4.11.1',
        'fsspec==2022.1.0',
        'jsonschema',
        'mlflow==1.26.1',
        'numpy',
        'pandas',
        'py4j',
        'pyarrow>=6.0',
        'pyspark==3.2.1',
        'pyyaml',
        'requests',
        'scikit-learn',
    ),
    'name': 'liga',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        'liga',
        'liga.internal',
        'liga.mlflow',
        'liga.numpy',
        'liga.registry',
        'liga.sklearn',
        'liga.sklearn.models',
        'liga.spark',
        'liga.spark.sql',
        'liga.spark.sql.generated',
        'liga.spark.types',
    ),
    'python_requires': '<3.10,>=3.8',
    'version': '0.2.0.dev7',
})
