
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T15:37:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "261b9eb3e58af8cab2c3bb7f55e79c5782d07eeb",
 "version": "2.10.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
