
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T13:11:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b42151d8bfe9c28be46d1ace7e0e2be26a4de06d",
 "version": "v23.02.00a230113"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
