
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T20:01:23+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "805a1137e6bb8ee39dcfef0a5d04d510be38492e",
 "version": "0.16.3.post3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
