# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/monitoring/monitoring_control_plane.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from truera.protobuf.druid import ingestion_spec_pb2 as truera_dot_protobuf_dot_druid_dot_ingestion__spec__pb2
from truera.protobuf.public.common import data_locator_pb2 as truera_dot_protobuf_dot_public_dot_common_dot_data__locator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9truera/protobuf/monitoring/monitoring_control_plane.proto\x12\x11truera.monitoring\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*truera/protobuf/druid/ingestion_spec.proto\x1a\x30truera/protobuf/public/common/data_locator.proto\"W\n\x16\x43reateIngestionRequest\x12)\n\x04spec\x18\x01 \x01(\x0b\x32\x1b.truera.druid.IngestionSpec\x12\x12\n\nproject_id\x18\x02 \x01(\t\"\x19\n\x17\x43reateIngestionResponse\",\n\x16ListDruidTablesRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"\x8e\x01\n\x0f\x44ruidTableEntry\x12\x18\n\x10\x64ruid_table_name\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x1a\n\x12\x64\x61ta_collection_id\x18\x03 \x01(\t\x12\x31\n\tdata_kind\x18\x04 \x01(\x0b\x32\x1e.truera.common.DataKindWrapper\"R\n\x17ListDruidTablesResponse\x12\x37\n\x0b\x64ruidTables\x18\x01 \x03(\x0b\x32\".truera.monitoring.DruidTableEntry2\x93\x02\n\x16MonitoringControlPlane\x12j\n\x0f\x43reateIngestion\x12).truera.monitoring.CreateIngestionRequest\x1a*.truera.monitoring.CreateIngestionResponse\"\x00\x12\x8c\x01\n\x0fListDruidTables\x12).truera.monitoring.ListDruidTablesRequest\x1a*.truera.monitoring.ListDruidTablesResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/druid-tables/{project_id}BJ\n)com.truera.protobuf.monitoring.managementB\x1bMonitoringControlPlaneProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.monitoring.monitoring_control_plane_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.truera.protobuf.monitoring.managementB\033MonitoringControlPlaneProtoP\001'
  _MONITORINGCONTROLPLANE.methods_by_name['ListDruidTables']._options = None
  _MONITORINGCONTROLPLANE.methods_by_name['ListDruidTables']._serialized_options = b'\202\323\344\223\002\034\022\032/druid-tables/{project_id}'
  _CREATEINGESTIONREQUEST._serialized_start=237
  _CREATEINGESTIONREQUEST._serialized_end=324
  _CREATEINGESTIONRESPONSE._serialized_start=326
  _CREATEINGESTIONRESPONSE._serialized_end=351
  _LISTDRUIDTABLESREQUEST._serialized_start=353
  _LISTDRUIDTABLESREQUEST._serialized_end=397
  _DRUIDTABLEENTRY._serialized_start=400
  _DRUIDTABLEENTRY._serialized_end=542
  _LISTDRUIDTABLESRESPONSE._serialized_start=544
  _LISTDRUIDTABLESRESPONSE._serialized_end=626
  _MONITORINGCONTROLPLANE._serialized_start=629
  _MONITORINGCONTROLPLANE._serialized_end=904
# @@protoc_insertion_point(module_scope)
