VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('14')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 1
MINOR_VERSION = 11
PATCH_VERSION = 202301140734
version_date = '2023/01/14 07:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
