
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T15:05:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "46e8c6d6d7432960d9836b85c1556198055cffa9",
 "version": "1.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
