
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T09:36:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e4f6cb48c96cd5fbe467187360aa36dbcc8d829",
 "version": "0.2.1.post0.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
