# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/generalFunctions',
                'doc_host': 'https://kaiguender.github.io',
                'git_url': 'https://github.com/kaiguender/generalFunctions',
                'lib_path': 'generalFunctions'},
  'syms': { 'generalFunctions.core': {'generalFunctions.core.foo': ('core.html#foo', 'generalFunctions/core.py')},
            'generalFunctions.runModels': { 'generalFunctions.runModels.foo': ( 'runmodels_helperfunctions.html#foo',
                                                                                'generalFunctions/runModels.py'),
                                            'generalFunctions.runModels.getCostsNV': ( 'runmodels_helperfunctions.html#getcostsnv',
                                                                                       'generalFunctions/runModels.py'),
                                            'generalFunctions.runModels.loadDataToContinue': ( 'runmodels_helperfunctions.html#loaddatatocontinue',
                                                                                               'generalFunctions/runModels.py'),
                                            'generalFunctions.runModels.tunePredictSave': ( 'runmodels_helperfunctions.html#tunepredictsave',
                                                                                            'generalFunctions/runModels.py')}}}
