
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-09T17:49:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f4a2e780f23f450d447f253e378dda4e2c687dd",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
