
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T13:44:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e6fbb40cf32d0a16f50f8e1ff35b3d28753f8ac",
 "version": "v0.0.1-beta.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
