
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T16:34:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "215317b48a0e76365f3fe75aff0a82090eefede9",
 "version": "2.5.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
