
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-05T11:33:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e122c9b56fd9b1c6b35a5741ee87d18ad505829",
 "version": "0.4.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
