
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-23T17:03:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fd1f97b6f4f0fa3e2f750dfc6757ddd909a537e",
 "version": "3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
