
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T19:43:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a7e43fa9bee276260df1af21cc80746ddee7596",
 "version": "0.2.59.post0.dev20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
