
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T01:44:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa36d1624619091f8ebe994258add8d96b491473",
 "version": "0.2.59.post0.dev30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
