from bittrade_kraken_websocket.connection.generic import EnhancedWebsocket as EnhancedWebsocket, WEBSOCKET_STATUS as WEBSOCKET_STATUS, WebsocketBundle as WebsocketBundle
from bittrade_kraken_websocket.connection.status import Status as Status, WEBSOCKET_AUTHENTICATED as WEBSOCKET_AUTHENTICATED, WEBSOCKET_CLOSED as WEBSOCKET_CLOSED, WEBSOCKET_OPENED as WEBSOCKET_OPENED, WEBSOCKET_SYSTEM_ONLINE as WEBSOCKET_SYSTEM_ONLINE
from reactivex import Observable as Observable
from typing import Callable, List, Optional, Tuple

ReadyMessage = Tuple[EnhancedWebsocket, bool]

def filter_socket_status_only() -> Callable[[Observable[WebsocketBundle]], Observable[WebsocketBundle]]: ...
def map_socket_only() -> Callable[[Observable[Union[WebsocketBundle, ReadyMessage]]], Observable[EnhancedWebsocket]]: ...
def connected_socket() -> Callable[[Observable[WebsocketBundle]], Observable[EnhancedWebsocket]]: ...
def ready_socket(up_statuses: Optional[List[Status]] = ..., down_statuses: Optional[List[Status]] = ...) -> Callable[[Observable[WebsocketBundle]], Observable[ReadyMessage]]: ...
def authenticated_socket() -> Callable[[Observable[WebsocketBundle]], Observable[EnhancedWebsocket]]: ...
