from bittrade_kraken_websocket.connection.generic import WebsocketBundle
from reactivex import ConnectableObservable, Observable
from reactivex.abc import SchedulerBase
from typing import Literal, Optional, overload

@overload
def private_websocket_connection() -> ConnectableObservable[WebsocketBundle]: ...
@overload
def private_websocket_connection(*, scheduler: Optional[SchedulerBase]) -> ConnectableObservable[WebsocketBundle]: ...
@overload
def private_websocket_connection(*, reconnect: bool) -> ConnectableObservable[WebsocketBundle]: ...
@overload
def private_websocket_connection(*, reconnect: bool, scheduler: Optional[SchedulerBase]) -> ConnectableObservable[WebsocketBundle]: ...
@overload
def private_websocket_connection(*, reconnect: bool, shared: Literal[True], scheduler: Optional[SchedulerBase]) -> ConnectableObservable[WebsocketBundle]: ...
@overload
def private_websocket_connection(*, reconnect: bool, shared: Literal[False], scheduler: Optional[SchedulerBase]) -> Observable[WebsocketBundle]: ...
