from bittrade_kraken_websocket.connection.generic import WebsocketBundle as WebsocketBundle
from reactivex import ConnectableObservable as ConnectableObservable, Observable as Observable
from reactivex.abc import SchedulerBase as SchedulerBase
from typing import Literal, Optional, overload

@overload
def public_websocket_connection() -> ConnectableObservable[WebsocketBundle]: ...
@overload
def public_websocket_connection(*, scheduler: Optional[SchedulerBase]) -> ConnectableObservable[WebsocketBundle]: ...
@overload
def public_websocket_connection(*, reconnect: bool, scheduler: Optional[SchedulerBase]) -> ConnectableObservable[WebsocketBundle]: ...
@overload
def public_websocket_connection(*, reconnect: bool, shared: Literal[True], scheduler: Optional[SchedulerBase]) -> ConnectableObservable[WebsocketBundle]: ...
@overload
def public_websocket_connection(*, reconnect: bool, shared: Literal[False], scheduler: Optional[SchedulerBase]) -> Observable[WebsocketBundle]: ...
