# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infrastructuresettings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cinfrastructuresettings.proto\x12\x08\x64\x61takube\"\xda\x01\n\x1fSparkConnectionConfigurationDto\x12\x0b\n\x03url\x18\x01 \x01(\t\x12i\n\x18\x63onfigurationVariableMap\x18\x02 \x03(\x0b\x32G.datakube.SparkConnectionConfigurationDto.ConfigurationVariableMapEntry\x1a?\n\x1d\x43onfigurationVariableMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x19S3StorageConfigurationDto\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x04 \x01(\t\"W\n\x15KafkaConfigurationDto\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\tBp\nPcom.datomize.datomizer.backend.components.management.dto.infrastructure.settingsB\x1cInfrastructureSettingsProtosb\x06proto3')



_SPARKCONNECTIONCONFIGURATIONDTO = DESCRIPTOR.message_types_by_name['SparkConnectionConfigurationDto']
_SPARKCONNECTIONCONFIGURATIONDTO_CONFIGURATIONVARIABLEMAPENTRY = _SPARKCONNECTIONCONFIGURATIONDTO.nested_types_by_name['ConfigurationVariableMapEntry']
_S3STORAGECONFIGURATIONDTO = DESCRIPTOR.message_types_by_name['S3StorageConfigurationDto']
_KAFKACONFIGURATIONDTO = DESCRIPTOR.message_types_by_name['KafkaConfigurationDto']
SparkConnectionConfigurationDto = _reflection.GeneratedProtocolMessageType('SparkConnectionConfigurationDto', (_message.Message,), {

  'ConfigurationVariableMapEntry' : _reflection.GeneratedProtocolMessageType('ConfigurationVariableMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SPARKCONNECTIONCONFIGURATIONDTO_CONFIGURATIONVARIABLEMAPENTRY,
    '__module__' : 'infrastructuresettings_pb2'
    # @@protoc_insertion_point(class_scope:datakube.SparkConnectionConfigurationDto.ConfigurationVariableMapEntry)
    })
  ,
  'DESCRIPTOR' : _SPARKCONNECTIONCONFIGURATIONDTO,
  '__module__' : 'infrastructuresettings_pb2'
  # @@protoc_insertion_point(class_scope:datakube.SparkConnectionConfigurationDto)
  })
_sym_db.RegisterMessage(SparkConnectionConfigurationDto)
_sym_db.RegisterMessage(SparkConnectionConfigurationDto.ConfigurationVariableMapEntry)

S3StorageConfigurationDto = _reflection.GeneratedProtocolMessageType('S3StorageConfigurationDto', (_message.Message,), {
  'DESCRIPTOR' : _S3STORAGECONFIGURATIONDTO,
  '__module__' : 'infrastructuresettings_pb2'
  # @@protoc_insertion_point(class_scope:datakube.S3StorageConfigurationDto)
  })
_sym_db.RegisterMessage(S3StorageConfigurationDto)

KafkaConfigurationDto = _reflection.GeneratedProtocolMessageType('KafkaConfigurationDto', (_message.Message,), {
  'DESCRIPTOR' : _KAFKACONFIGURATIONDTO,
  '__module__' : 'infrastructuresettings_pb2'
  # @@protoc_insertion_point(class_scope:datakube.KafkaConfigurationDto)
  })
_sym_db.RegisterMessage(KafkaConfigurationDto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\nPcom.datomize.datomizer.backend.components.management.dto.infrastructure.settingsB\034InfrastructureSettingsProtos'
  _SPARKCONNECTIONCONFIGURATIONDTO_CONFIGURATIONVARIABLEMAPENTRY._options = None
  _SPARKCONNECTIONCONFIGURATIONDTO_CONFIGURATIONVARIABLEMAPENTRY._serialized_options = b'8\001'
  _SPARKCONNECTIONCONFIGURATIONDTO._serialized_start=43
  _SPARKCONNECTIONCONFIGURATIONDTO._serialized_end=261
  _SPARKCONNECTIONCONFIGURATIONDTO_CONFIGURATIONVARIABLEMAPENTRY._serialized_start=198
  _SPARKCONNECTIONCONFIGURATIONDTO_CONFIGURATIONVARIABLEMAPENTRY._serialized_end=261
  _S3STORAGECONFIGURATIONDTO._serialized_start=263
  _S3STORAGECONFIGURATIONDTO._serialized_end=355
  _KAFKACONFIGURATIONDTO._serialized_start=357
  _KAFKACONFIGURATIONDTO._serialized_end=444
# @@protoc_insertion_point(module_scope)
