
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T17:06:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e687a89573f6e210efc62933595342df7014f66e",
 "version": "2.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
