# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import unittest
import urllib.request
import numpy
import infery.common.data_classes.inferencer_benchmark_result
import infery.common.data_interface.files_data_interface
import infery.common.enums.framework_type
import infery.common.enums.inference_hardware
import infery.common.exceptions
import infery.common.logger_factory
import infery.inference.config
import infery.inference.infery_manager
import torch
import infery
import tests.installation_tests.test_infery_installation
import tests.unit_tests.test_inferencers.test_keras_inferencer
import tests.unit_tests.test_inferencers.test_onnx_inferencer
import tests.unit_tests.test_inferencers.test_openvino_inferencer
import tests.unit_tests.test_inferencers.test_tensorflow_inferencer
import tests.unit_tests.test_inferencers.test_torchscript_inferencer
import tests.unit_tests.test_model_benchmarks_print
import tests.unit_tests.test_inferencers.test_trt_inferencer
import tests.test_utils.abstract_test_suite
import tests.e2e_tests.test_infery_manager
import tests.unit_tests.test_inferencers.test_tflite_inferencer
import tests.unit_tests.test_inferencers.test_pytorch_inferencer
import datetime
import subprocess
import json
import infery_tool_logger
import infery_tool_parser
import pandas
import argparse
import infery_tool_regressor
import deci_infra.data_connection.slack_manager
import deci_infra.data_connection.s3_connector
import infery_tool_benchmarker
import infery_tool_plotter
import infery_tool_slacker
import pathlib
import tempfile
import tests.infery_test_suite
import venv
import shutil
import random
import cv2
import math
import torchvision
import PIL
import urllib
import uuid
import pickle
import xml.etree
import infery.frameworks.openvino_inferencer
import enum
import tensorrt
import time
import abc
import contextlib
import infery.frameworks.base_inferencer
import infery.common.data_classes.tensor_metadata
import os.path
import infery.frameworks.coreml_inferencer
import tests.unit_tests.test_inferencers.test_abstract_inferencer
import infery.frameworks.keras_inferencer
import infery.frameworks.onnx_inferencer
import tests.test_utils.coco_utils
import tests.test_utils.downloads_helpers
import onnxruntime
import torch.nn
import infery.frameworks.pytorch_inferencer
import tensorflow
import infery.frameworks.tensorflow_inferencer
import infery.frameworks.tflite_inferencer
import infery.frameworks.torchscript_inferencer
import gc
import infery.frameworks.trt_inferencer
import nvtx
import platform
import GPUtil

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

