
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-09T05:58:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "67860566ea0852c5503d3553d8d08424799cc188",
 "version": "1.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
