
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T15:28:49+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "70f5128d4dc775df6357281d057c4bcc4578bd0c",
 "version": "0.17.2a9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
