
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-14T15:14:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d75a5e6b670ce5b592989a9609431936d3e7149",
 "version": "2023.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
