
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T09:26:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf6dd9c3d33546fdc06e9ed3b002b76ea7bbbc2d",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
