
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-06T14:50:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "74b4557df64fbf42461060b4bb536a6b5249202e",
 "version": "v23.02.00a230110"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
