
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T19:05:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdb34aedf22151c74c70abacef511d45b25445f0",
 "version": "0.2.60"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
