"""This file is generated by setuptools-generate.
The information comes from pyproject.toml.
It provide some metainfo for docs/conf.py to build documents and
help2man to build man pages.
"""

# For docs/conf.py
project = "python-wakatime"
author = """Wu Zhenyu <wuzhenyu@ustc.edu> """
copyright = "2023"

# For help2man
DESCRIPTION = "wakatime plugin for python"
EPILOG = "Report bugs to https://github.com/Freed-Wu/python-wakatime/issues"
# format __version__ by yourself
VERSION = """python-wakatime {__version__}
Copyright (C) 2023
Written by Wu Zhenyu <wuzhenyu@ustc.edu> """