# coding: utf-8

"""
    Common Fate

    Common Fate API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from jhc_cf_sdk_test.paths.api_v1_admin_requests_request_id.get import AdminGetRequest
from jhc_cf_sdk_test.paths.api_v1_requests_request_id_cancel.post import UserCancelRequest
from jhc_cf_sdk_test.paths.api_v1_favorites.post import UserCreateFavorite
from jhc_cf_sdk_test.paths.api_v1_requests.post import UserCreateRequest
from jhc_cf_sdk_test.paths.api_v1_favorites_id.delete import UserDeleteFavorite
from jhc_cf_sdk_test.paths.api_v1_requests_request_id_access_instructions.get import UserGetAccessInstructions
from jhc_cf_sdk_test.paths.api_v1_access_rules_rule_id.get import UserGetAccessRule
from jhc_cf_sdk_test.paths.api_v1_access_rules_rule_id_approvers.get import UserGetAccessRuleApprovers
from jhc_cf_sdk_test.paths.api_v1_requests_request_id_access_token.get import UserGetAccessToken
from jhc_cf_sdk_test.paths.api_v1_favorites_id.get import UserGetFavorite
from jhc_cf_sdk_test.paths.api_v1_users_me.get import UserGetMe
from jhc_cf_sdk_test.paths.api_v1_requests_request_id.get import UserGetRequest
from jhc_cf_sdk_test.paths.api_v1_users_user_id.get import UserGetUser
from jhc_cf_sdk_test.paths.api_v1_access_rules.get import UserListAccessRules
from jhc_cf_sdk_test.paths.api_v1_favorites.get import UserListFavorites
from jhc_cf_sdk_test.paths.api_v1_requests_request_id_events.get import UserListRequestEvents
from jhc_cf_sdk_test.paths.api_v1_requests.get import UserListRequests
from jhc_cf_sdk_test.paths.api_v1_requests_past.get import UserListRequestsPast
from jhc_cf_sdk_test.paths.api_v1_requests_upcoming.get import UserListRequestsUpcoming
from jhc_cf_sdk_test.paths.api_v1_access_rules_lookup.get import UserLookupAccessRule
from jhc_cf_sdk_test.paths.api_v1_requests_request_id_review.post import UserReviewRequest
from jhc_cf_sdk_test.paths.api_v1_requests_requestid_revoke.post import UserRevokeRequest
from jhc_cf_sdk_test.paths.api_v1_favorites_id.put import UserUpdateFavorite


class EndUserApi(
    AdminGetRequest,
    UserCancelRequest,
    UserCreateFavorite,
    UserCreateRequest,
    UserDeleteFavorite,
    UserGetAccessInstructions,
    UserGetAccessRule,
    UserGetAccessRuleApprovers,
    UserGetAccessToken,
    UserGetFavorite,
    UserGetMe,
    UserGetRequest,
    UserGetUser,
    UserListAccessRules,
    UserListFavorites,
    UserListRequestEvents,
    UserListRequests,
    UserListRequestsPast,
    UserListRequestsUpcoming,
    UserLookupAccessRule,
    UserReviewRequest,
    UserRevokeRequest,
    UserUpdateFavorite,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
