"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StatusCode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _StatusCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StatusCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _StatusCode.ValueType  # 0
    CANCELLED: _StatusCode.ValueType  # 1
    UNKNOWN: _StatusCode.ValueType  # 2
    INVALID_ARGUMENT: _StatusCode.ValueType  # 3
    DEADLINE_EXCEEDED: _StatusCode.ValueType  # 4
    NOT_FOUND: _StatusCode.ValueType  # 5
    ALREADY_EXISTS: _StatusCode.ValueType  # 6
    PERMISSION_DENIED: _StatusCode.ValueType  # 7
    RESOURCE_EXHAUSTED: _StatusCode.ValueType  # 8
    FAILED_PRECONDITION: _StatusCode.ValueType  # 9
    ABORTED: _StatusCode.ValueType  # 10
    OUT_OF_RANGE: _StatusCode.ValueType  # 11
    UNIMPLEMENTED: _StatusCode.ValueType  # 12
    INTERNAL: _StatusCode.ValueType  # 13
    UNAVAILABLE: _StatusCode.ValueType  # 14
    DATA_LOSS: _StatusCode.ValueType  # 15
    UNAUTHENTICATED: _StatusCode.ValueType  # 16
class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper):
    """StatusCode must match pw::Status in pw_status."""
    pass

OK: StatusCode.ValueType  # 0
CANCELLED: StatusCode.ValueType  # 1
UNKNOWN: StatusCode.ValueType  # 2
INVALID_ARGUMENT: StatusCode.ValueType  # 3
DEADLINE_EXCEEDED: StatusCode.ValueType  # 4
NOT_FOUND: StatusCode.ValueType  # 5
ALREADY_EXISTS: StatusCode.ValueType  # 6
PERMISSION_DENIED: StatusCode.ValueType  # 7
RESOURCE_EXHAUSTED: StatusCode.ValueType  # 8
FAILED_PRECONDITION: StatusCode.ValueType  # 9
ABORTED: StatusCode.ValueType  # 10
OUT_OF_RANGE: StatusCode.ValueType  # 11
UNIMPLEMENTED: StatusCode.ValueType  # 12
INTERNAL: StatusCode.ValueType  # 13
UNAVAILABLE: StatusCode.ValueType  # 14
DATA_LOSS: StatusCode.ValueType  # 15
UNAUTHENTICATED: StatusCode.ValueType  # 16
global___StatusCode = StatusCode

