
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T15:57:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "23bb144aa8710a302868bbc008bf1dd6a29b0ef5",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
