# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/public/common/row.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from truera.protobuf.public.common import schema_pb2 as truera_dot_protobuf_dot_public_dot_common_dot_schema__pb2
from truera.protobuf.public import truera_custom_options_pb2 as truera_dot_protobuf_dot_public_dot_truera__custom__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'truera/protobuf/public/common/row.proto\x12\rtruera.common\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*truera/protobuf/public/common/schema.proto\x1a\x32truera/protobuf/public/truera_custom_options.proto\"c\n\x11SchemaEmbeddedRow\x12,\n\x06schema\x18\x01 \x03(\x0b\x32\x1c.truera.common.ColumnDetails\x12 \n\x04rows\x18\x02 \x03(\x0b\x32\x12.truera.common.Row\"A\n\x03Row\x12\r\n\x05index\x18\x01 \x01(\x03\x12+\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\x1a.truera.common.ColumnValue\"\xd4\x02\n\x0b\x43olumnValue\x12\x14\n\x0c\x63olumn_index\x18\x01 \x01(\x05\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x14\n\nbyte_value\x18\x03 \x01(\rH\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12\x15\n\x0b\x66loat_value\x18\x05 \x01(\x02H\x00\x12\x13\n\tint_value\x18\x06 \x01(\x05H\x00\x12\x14\n\nlong_value\x18\x07 \x01(\x03H\x00\x12\x15\n\x0bshort_value\x18\x08 \x01(\x05H\x00\x12\x16\n\x0cstring_value\x18\t \x01(\tH\x00\x12\x35\n\x0ftimestamp_value\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12\x34\n\x0enull_indicator\x18\x0b \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x42\r\n\x0btyped_valueB,\n\x1a\x63om.truera.protobuf.commonB\x08RowProtoP\x01\x90\x82\x19\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.public.common.row_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.truera.protobuf.commonB\010RowProtoP\001\220\202\031\001'
  _SCHEMAEMBEDDEDROW._serialized_start=217
  _SCHEMAEMBEDDEDROW._serialized_end=316
  _ROW._serialized_start=318
  _ROW._serialized_end=383
  _COLUMNVALUE._serialized_start=386
  _COLUMNVALUE._serialized_end=726
# @@protoc_insertion_point(module_scope)
