
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T10:37:01+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb1dd837690258a0248988d5575f3b6b0e4a70d0",
 "version": "2.10.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
