
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T20:08:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "29c905c9b009b2a78f450654e306b2d4a00b2e8b",
 "version": "0.0.77"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
