
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T19:09:25+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac894cbfa957b42c9e5d4f2bb228d75a3b91d2c5",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
