
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T22:47:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "06f3006ab7a0a5e72423267c47db767c004eda3f",
 "version": "0.13.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
