
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T14:20:35+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a60e2bc3056a1ec0f3b9c7ec4d0b8a49f330b069",
 "version": "0.16.3.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
