
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-09T23:16:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b530c3314b926ebe61b151b1f677fbfba4e46976",
 "version": "1.46.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
