
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T16:33:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3e1afa5c3347b859c7527c7d8dbf730dc6b16e2",
 "version": "0.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
