
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T20:43:09+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef8019858742a3718a456affee96cc432ad34721",
 "version": "0.1.40.post0.dev72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
