
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T10:41:59-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c5993e3e772ac2660d40dd9af03ca4f3db8a7e7",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
