
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T04:49:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ab64f5de95cdda5c05a27e7269cfcdc20bb82b5",
 "version": "1.18.0.post0.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
