
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T13:56:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "026b63fb689c909a97119c8a9bfa336a585be14a",
 "version": "0.15.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
