
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T08:59:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8929cda606e66d06494d6c617ae47d4f9b6fc408",
 "version": "1.17.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
