
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T11:30:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc321cdc50866043b8d8f95999c827fab291491e",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
