from _typeshed import Incomplete

WEBSOCKET_OPENED: str
WEBSOCKET_SYSTEM_ONLINE: str
WEBSOCKET_SYSTEM_MAINTENANCE: str
WEBSOCKET_SYSTEM_CANCEL_ONLY: str
WEBSOCKET_SYSTEM_POST_ONLY: str
WEBSOCKET_SYSTEM_LIMIT_ONLY: str
WEBSOCKET_CLOSED: str
WEBSOCKET_AUTHENTICATED: str
Status: Incomplete
