"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Tokenization:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _TokenizationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Tokenization.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TOKENIZATION_OPTIONAL: _Tokenization.ValueType  # 0
    """The field may contain plain text or any type of tokenized data (binary or
    prefixed Base64).
    """

class Tokenization(_Tokenization, metaclass=_TokenizationEnumTypeWrapper):
    pass

TOKENIZATION_OPTIONAL: Tokenization.ValueType  # 0
"""The field may contain plain text or any type of tokenized data (binary or
prefixed Base64).
"""

global___Tokenization = Tokenization


FORMAT_FIELD_NUMBER: builtins.int
format: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, global___Tokenization.ValueType]
"""The field number was randomly selected from the reserved, internal use
field numbers (50000-99999).
TODO(b/234886465): Register with the Protobuf Global Extension Registry:
    https://github.com/protocolbuffers/protobuf/blob/HEAD/docs/options.md
"""
