
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T09:41:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a76041a6b0ef0eebc5d5c39f5f8b759651eb0fa5",
 "version": "1.13.102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
