
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T12:33:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d87d61cdc9f29998fb26af354fa7e6a897760103",
 "version": "1.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
