# Generated by Django 4.1.5 on 2023-01-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_uuid_artist_uuid_track_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='thumbs',
            field=models.IntegerField(
                choices=[
                    (-1, 'Thumbs down'),
                    (0, 'No opinion'),
                    (1, 'Thumbs up'),
                ],
                default=0,
            ),
        ),
    ]
