
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T17:29:04-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bdb4ec5b81e459bc3442d35a57cb3ab1a53deb5",
 "version": "7.4.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
