
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-14T02:16:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "412ec54f0b2c0faf14a74af158b537ae58796f5a",
 "version": "0.2.60.post0.dev19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
