
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-12T04:23:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cfaa8b476992e95d901dc29cab1c70ccac4f510",
 "version": "1.18.0.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
