from lumipy.test.unit.utilities import temp_file_manager

from .atlas.test_atlas import TestAtlas
from .atlas.test_field_description import TestFieldDescription
from .atlas.test_provider_description import TestProviderFactory
from .common.test_lockable import TestLockable
from .expression.case.test_case_expression import TestCaseExpression
from .expression.column.test_column_alias import TestAliasedColumns
from .expression.column.test_column_literal import TestLiteralColumns
from .expression.column.test_column_ordering import TestColumnOrdering
from .expression.column.test_column_prefix import TestPrefixColumns
from .expression.column.test_source_column import TestSourceColumn
from .expression.column_op.test_column_methods import TestColumnFunctionMethods
from .expression.column_op.test_column_op_misc import TestColumnBinaryScalarOp
from .expression.table.test_aliased_table import TestAliasedTable
from .expression.table.test_join_table import TestJoinTableClass
from .expression.table.test_provider_table import TestProviderClasses
from .expression.table_op.test_aggregate import TestGroupAggregation
from .expression.table_op.test_docstrings import TestTableOpDocumentation
from .expression.table_op.test_group_by import TestGroupBy
from .expression.table_op.test_having import TestHaving
from .expression.table_op.test_limit import TestLimit
from .expression.table_op.test_order_by import TestOrderBy
from .expression.table_op.test_row_set_ops import TestRowSetOpExpressions
from .expression.table_op.test_sample import TestTableSample
from .expression.table_op.test_select import TestSelect
from .expression.table_op.test_setup_view import TestLimit
from .expression.table_op.test_where import TestWhere
from .expression.variable.test_dependency_resolution import TestAtVariables
from .expression.variable.test_scalar_variable import TestScalarVariable
from .expression.variable.test_table_literal import TestTableLiterals
from .expression.variable.test_table_variables import TestTableVariable
from .expression.window.test_frame import TestWindowFrame
from .expression.window.test_order import TestWindowOrdering
from .expression.window.test_over import TestOver
from .expression.window.test_partition import TestWindowPartition
from .expression.window.test_window_methods import TestWindowFunctionMethods
from .expression.window.test_window_prefixing import TestWindowPrefixing
from .provider.test_filter_translation import TestFilterTranslation
from .provider.test_python_providers import TestLocalProviderInfra
