
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-13T23:31:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aed0212ed88e0c62623aa479c3864df8d7596356",
 "version": "0.2.60.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
