
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T14:13:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b698394d3f98b64ca4f51b09cb0c9b20d2649170",
 "version": "2023.1rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
