
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-10T17:39:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a6783662634d1292a61b271f5d2b8240c845521",
 "version": "2023.14rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
