
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T20:34:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b2f2f1133276b4a7f17cce9600e5f7c20f0791e",
 "version": "0.2.60.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
